### PR TITLE
Updated Eventbus rules

### PR DESCRIPTION
**Pull request by icechen1**
The new version of eventbus introduces some breaking changes in the API, and thus some new rules are now needed

### CODE REVIEW

**Comment by krschultz** [comment]
Can we put this in a separate file?

**Comment by Jawnnypoo** [comment]
Nice, @icechen1 just what I needed. And yes, I would agree that this should be under eventbus 3.0, like what is done with Retrofit 1.x vs 2.x

**Comment by icechen1** [comment]
it's now in a different file!

**Comment by krschultz** [comment]
Thanks!

**Pull request merged**
